name: learn_n
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  flex_color_picker: ^3.6.0
  audioplayers: ^6.1.0
  intl: ^0.20.1
  lottie: ^3.3.1
  liquid_swipe: ^3.1.0
  do_not_disturb: ^1.0.3
  animated_bottom_navigation_bar: ^1.3.3
  google_generative_ai: ^0.4.6
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.1
  go_router: ^14.8.1
  flutter_markdown: ^0.7.7
  file_picker: ^10.1.2
  syncfusion_flutter_pdf: ^29.1.38
  just_audio: ^0.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5



flutter:

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/lottie/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_icon.png"
  min_sdk_android: 21