name: learn_n
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  flex_color_picker: ^3.6.0
  dotted_border: ^2.1.0
  flutter_local_notifications: ^18.0.1
  flutter_datetime_picker: ^1.5.1
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  intl: ^0.20.1
  lottie: ^3.3.1
  animations: ^2.0.11
  liquid_swipe: ^3.1.0
  flutter_heatmap_calendar: ^1.0.5
  do_not_disturb: ^1.0.3
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  animated_bottom_navigation_bar: ^1.3.3
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.1
  provider: ^6.1.2
  timezone: ^0.10.0
  google_generative_ai: ^0.4.6
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  http: ^1.3.0
  flutter_chat_ui: ^1.6.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

  uses-material-design: true

  assets:
    - assets/logo_icon.png
    - assets/wrong_sf.mp3
    - assets/correct_sf.mp3
    - assets/rank1.json
    - assets/rank2.json
    - assets/rank3.json
    - assets/rank4.json
    - assets/streakpet1.json
    - assets/streakpet2.json
    - assets/streakpet3.json
    - assets/makequiz.json
    - assets/leaderboard.json
    - assets/digitalizequiz.json
    - assets/folders.json
    - assets/notification.json
    - assets/notification.mp3
    - assets/logo.png
    - assets/tiktok.json
    - assets/hints.json
    - assets/effectbg.json
    - assets/dnd.json
    - assets/theme.json
    - assets/confetti.json
    - assets/award.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_icon.png"