// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxHfuprInJzWNngGwRAHzYm0ByiBPbB1c',
    appId: '1:1031285993587:web:3ad51e4e6c175372133a06',
    messagingSenderId: '1031285993587',
    projectId: 'learn-n-app',
    authDomain: 'learn-n-app.firebaseapp.com',
    storageBucket: 'learn-n-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa66MXSmcNQ312nfhFyfV3HszZ4n-fe7o',
    appId: '1:1031285993587:android:f7d84d73551d5de6133a06',
    messagingSenderId: '1031285993587',
    projectId: 'learn-n-app',
    storageBucket: 'learn-n-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMmXJCV3RE_2LUVQw67sE9RDpSEKunlmI',
    appId: '1:1031285993587:ios:1e0b9df9f80d8983133a06',
    messagingSenderId: '1031285993587',
    projectId: 'learn-n-app',
    storageBucket: 'learn-n-app.firebasestorage.app',
    iosBundleId: 'com.example.learnn',
  );

}